### ISSUE TITLE
Throws 'FormatException: Invalid Base32 characters' when padding is missing

### ISSUE THREAD

**Issue by EsaiasTilly** [Daegalus/dart-base32#11]
When providing a Base32 string to `base32.decode` such as `ADWADWADWADDWADWADDWADA` an error is thrown. The error states `Invalid Base32 characters` which is incorrect as the issue is with padding, not invalid characters.

A solution could be to automatically add padding to strings, or throw another, more explanatory error message to prevent hours of debugging.

A solution found [here](https://gist.github.com/mndrix/b2494ebefd916c71ded5).

**Comment by Daegalus** [comment]
Oof, ok, I'll fix this later today. That is a regression with all the changes I made recently. My apologies. I will also add a test to catch future regressions like this.

**Comment by Daegalus** [comment]
Ok, this should be fixed in 2.1.3, I auto pad to the appropriate length when needed for encodings that have padding. let me know if you have other issues.

**Comment by EsaiasTilly** [comment]
This works perfectly! Thank you for such a quick fix! :)
