### ISSUE TITLE
decode() does not handle non base32 characters correctly

### ISSUE THREAD

**Issue by timosturm** [Daegalus/dart-base32#7]
When decoding strings such as "00000000" the result will be [0, 0, 0, 0, 0]. In fact any string of length eight that consists of non-base32 characters will have the same result.

I think that ideally a string that contains such characters should not be decoded, instead a FormatException should be thrown.

**Comment by Daegalus** [comment]
Good catch, I will take a look at this sometime this week or weekend, its kind of busy and I am visiting family for thanksgiving and staying there the whole week, so I will have plenty of time to fix this next week if I don't get to it this week. Sorry if it takes that long.

**Comment by Daegalus** [comment]
Should be fixed in 1.1 throwing a format exception. had to fix a lot more too.

**Comment by timosturm** [comment]
Thank you for your fast response. And happy holidays.
