### ISSUE TITLE
base32hex support

### ISSUE THREAD

**Issue by MartinHlavna** [Daegalus/dart-base32#8]
Hello,

any plans to support base32hex? Algo should be the same, just with different mappings.

**Comment by Daegalus** [comment]
I see no harm in it. Would take me a bit to add support for encodings but I'll add it soon.

**Comment by MartinHlavna** [comment]
Many thanks!

**Comment by Daegalus** [comment]
2.1.0 released with Base32Hex, Crockford, z-base-32, and Geohash variant support. Give it a shot and let me know if you have any issues.

https://pub.dev/packages/base32/versions/2.1.0
