### ISSUE TITLE
Crockford encoding should ignore hyphens in the string when decoding

### ISSUE THREAD

**Issue by mark-dropbear** [Daegalus/dart-base32#9]
Just came across the library today and already got a lot out of it thank you! I ran into one small issue described below. Please let me know if you have any questions at all.

```dart
void test() {
    const validIdentifier = 'SF27N947DKQ1CHCF=';
    const validIdentiferWithHyphens = 'SF27-N947-DKQ1-CHCF-';

    // This passes
    base32.decode(validIdentifier, encoding: Encoding.crockford);

    // This fails
    base32.decode(validIdentiferWithHyphens, encoding: Encoding.crockford);
  }
```

> Hyphens (-) can be inserted into symbol strings. This can partition a string into manageable pieces, improving readability by helping to prevent confusion. Hyphens are ignored during decoding. An application may look for hyphens to assure symbol string correctness.

**Source:** http://www.crockford.com/base32.html

**Comment by Daegalus** [comment]
Ah good catch, I just recently added support for non standard variants and didn't read too deeply into the differences. Just looked at the wiki for the character set and padding.

I'll update the code to handle hyphens. Give me a day or 2.

**Comment by Daegalus** [comment]
All set, v2.1.1 is published and should fix this issue. Let me know if you hit any other problems
